config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'articles#index'
  resources :articles do
    resources :comments
  end
  resources :tags
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments , dependent: :destroy
  has_many :taggings , dependent: :destroy
  has_many :tags , through: :taggings , dependent: :destroy

  has_attached_file :image, dependent: :destroy
  validates_attachment_content_type :image, :content_type => ['image/jpg', "image/jpeg","image/png"]

  def tag_list
    self.tags.collect do

    |tags| tags.name end.join(",")
  end

  def tag_list=(tag_string)
    entered_tags = tag_string.split(",").collect { |t| t.strip.downcase }.uniq
    new_tags = entered_tags.collect { |tags| Tag.find_or_create_by(name: tags) }
    self.tags = new_tags
    
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings,  dependent: :destroy
  has_many :articles, through: :taggings,  dependent: :destroy
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @article = Article.all
  end

  def show
   @article = Article.find(params[:id])
   @comment = Comment.new
   @comment.article_id = @article.id
  end

  def new
    @article = Article.new

  end

  def create
    @article = Article.new(article_params)
    @article.save
    flash[:notice] = "New Article #{@article.title} was created"
    redirect_to article_path(@article)

  end

  def edit
      @article = Article.find(params[:id])
  end

  def update
      @articles = Article.find(params[:id])
      @article = Article.update(article_params)
      flash.notice = "Hi there #{@articles.title} was updated"
      redirect_to article_path(@article)
  end


  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash[:notice] = "Article #{@article.title} was deleted "
    redirect_to '/articles'
  end


  private
  def article_params
    params.require(:article).permit(:title, :body,:tag_list, :image)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]
    @comment.save
    redirect_to article_path(@comment.article_id)
  end

  def destroy

    @comment = Comment.find(params[:article_id])
    flash[:notice] = "your comment was deleted"
    @comment.destroy
    redirect_to article_path(@comment.article)
  end

  def show

  end


  private
  def comment_params
    params.require(:comment).permit(:aurthor_name, :body)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
  end

  def show
    @tags = Tag.find(params[:id])
  end

  def destroy
    @tag =  Tag.find(params[:id])
    @tag.destroy
    redirect_to '/tags'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_form.erb
<div>
  <%= form_for(@article , html:{multipart: true}) do |f| %>
    <ul>
      <% @article.errors.full_messages.each do |error| %>
        <li> <%= error %></li>
      <%end %>
    </ul>
    <p><%= f.label :title %>  </p>
    <p><%= f.text_field :title %>  </p>

    <p><%= f.label :body %>  </p>
    <p><%= f.text_area :body %>  </p>

    <p>
      <%= f.label :tag_list %>
      <%= f.text_field :tag_list %>
    </p>
  <p>
    <%= f.label :image , "Enter image here" %>
    <%= f.file_field :image  %>
  </p>
    <p>
      <%= f.submit 'Create Post' %>
    </p>
  <%end %>
</div>

app/views/articles/edit.erb
<%= render 'articles/form' %>

app/views/articles/index.erb
<div class="container">
  <h1>Latest Articles</h1>
  <% @article.each do  |article| %>
   <h2 class="text text-danger text-center"> <%= article.title %></h2>
    <p class="text-info border text-center " >
      <%= article.body %>
    </p>
    <%= link_to 'Detail View', article_path(article), class: 'link ml-5 text-center'%>

  <%end %>
  <p>
    <%= link_to 'Create article', new_article_path %>
  </p>
</div>

app/views/articles/new.erb
<%= render 'articles/form' %>

app/views/articles/show.erb
<div class="container text-center">
  <h1>Article Details</h1>
  <h2><%= @article.title %> </h2>
  <p><%= image_tag  @article.image.url,  width: '1024' , class: "article-image" %></p>
  <h2> <%= @article.body %></h2>




</div>

<hr/>
<h1><%= @article.comments.count %> Comments </h1>
<%= render partial: 'comments/comment', collection: @article.comments %>
<%= render partial: 'comments/form' %>
<%= link_to "create new Article", new_article_path, class: "text-center text-success"%>
<%= link_to "edit your article ", edit_article_path(@article) %>
<%= link_to "delete" , article_path(@article), method: :delete ,data: {confirm: "Are you sure"} %>

<%@article.tags.each do |tags| %>

  <p>
    <%= link_to tags.name, tag_path(tags) %>
  </p>
<%end %>

app/views/comments/_comment.erb
<div>
<small>Posted <%=distance_of_time_in_words(comment.article.created_at, comment.created_at )  %></small>
<h4> <%= comment.aurthor_name %> </h4>
<p><%= comment.body %>   </p>
  <p>
    <%=  link_to  'delete ', article_comment_path(comment), method: :delete, data:{confirm: "are you sure you want to remove your comment"}, class: 'text-danger '%>
  </p>
</div>

app/views/comments/_form.erb
<h3>Leave some feedback</h3>

<%= form_for [@article ,@comment ] do |f|%>

  <p> <%= f.label :aurthor_namem, "Big Boss" %></p>
  <p> <%= f.text_field :aurthor_name %></p>

  <p> <%= f.label :body %></p>
  <p> <%= f.text_field :body %></p>

  <p>
    <%= f.submit "submit" %>
  </p>
<%end %>

app/views/layouts/_messages.erb
<p class="flash"> <%= flash.notice %>     </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <%=render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/tags/index.erb
<h1>Find articles by tags</h1>
<ul>
<% @tags.each do |tag| %>
  <l1>  <%= link_to tag.name, tag_path(tag) %></l1>
    <li><%= link_to "delete",tag_path(tag), method: :delete, data:{confirm:"Are you sure?", class: "text text-danger"} %></li>
  <%end%>
</ul>

app/views/tags/show.erb
<h1> select article by category</h1>

<ul>
  <% @tags.articles.each do |article| %>
  <li><%= link_to article.title, article_path(article ) %></li>

    <%end %>
</ul>